spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AndreiBabeanu/microservices-config-server
          username:
          password:
          clone-on-start: true
  application:
    name: configuration-server
server:
  port: 8888


